// 以后你主要改这个文件就能调整店铺、菜品和桌台。

window.SHOP_CONFIG = {
  menuVersion: "fuzhou-yantaishan-20260609-v2",
  name: "烟台山闽味小馆",
  subtitle: "福州菜、烟台山新派闽味，堂食外卖都可以",
  announcement: "主打福州菜与烟台山人气风味，现点现做，请留意取餐提醒",
  businessHours: "10:30-22:30",
  address: "福州仓山区仓前路 150 号附近",
  phone: "138-0000-8888",
  minOrderAmount: 20,
  packingFeePerDish: 1,
  deliveryFee: 6,
  deliveryRange: "3 公里",
  autoCancelMinutes: 15,
  serviceModes: ["dinein", "takeaway"],
};

window.TABLES = [
  { id: "A01", area: "大厅", seats: 2, status: "idle" },
  { id: "A08", area: "大厅", seats: 4, status: "idle" },
  { id: "B02", area: "包厢", seats: 8, status: "idle" },
];

window.MENU_ITEMS = [
  {
    id: "fotiaoqiang-cup",
    name: "佛跳墙小盅",
    category: "经典福州菜",
    price: 138,
    image: "🍲",
    tag: "招牌",
    rank: 1,
    stock: 18,
    monthlySales: 328,
    description: "鲍鱼、海参、蹄筋、瑶柱慢煨，单人小盅更适合日常点餐",
    specs: [
      { name: "规格", options: [{ label: "单人盅", priceDelta: 0 }, { label: "双人盅", priceDelta: 118 }] },
      { name: "汤底", options: [{ label: "经典浓汤", priceDelta: 0 }, { label: "花胶加浓", priceDelta: 38 }] },
    ],
  },
  {
    id: "fuzhou-lychee-pork",
    name: "福州荔枝肉",
    category: "经典福州菜",
    price: 58,
    image: "🍖",
    tag: "必点",
    rank: 2,
    stock: 46,
    monthlySales: 512,
    description: "酸甜红亮，外酥里嫩，保留老福州荔枝形刀工",
    specs: [
      { name: "份量", options: [{ label: "例份", priceDelta: 0 }, { label: "大份", priceDelta: 20 }] },
      { name: "口味", options: [{ label: "经典酸甜", priceDelta: 0 }, { label: "少甜", priceDelta: 0 }] },
    ],
  },
  {
    id: "nan-jian-gan",
    name: "南煎肝",
    category: "经典福州菜",
    price: 48,
    image: "🥢",
    tag: "老福州",
    rank: 5,
    stock: 34,
    monthlySales: 276,
    description: "猪肝薄切快煎，酸甜酱汁挂口，讲究火候",
    specs: [
      { name: "熟度", options: [{ label: "嫩口", priceDelta: 0 }, { label: "全熟", priceDelta: 0 }] },
      { name: "口味", options: [{ label: "经典酸甜", priceDelta: 0 }, { label: "少汁", priceDelta: 0 }] },
    ],
  },
  {
    id: "drunken-ribs",
    name: "十香醉排骨",
    category: "经典福州菜",
    price: 52,
    image: "🍖",
    tag: "人气",
    rank: 4,
    stock: 38,
    monthlySales: 368,
    description: "炸排骨裹十香酸甜汁，冷吃热吃都开胃",
    specs: [
      { name: "份量", options: [{ label: "例份", priceDelta: 0 }, { label: "大份", priceDelta: 18 }] },
      { name: "酱汁", options: [{ label: "标准", priceDelta: 0 }, { label: "多汁", priceDelta: 0 }] },
    ],
  },
  {
    id: "stir-fried-double-crisp",
    name: "爆炒双脆",
    category: "经典福州菜",
    price: 68,
    image: "🔥",
    tag: "锅气",
    rank: 8,
    stock: 28,
    monthlySales: 198,
    description: "腰花与海蜇头猛火快炒，脆嫩酸甜，适合下酒",
    specs: [
      { name: "口味", options: [{ label: "酸甜", priceDelta: 0 }, { label: "微辣", priceDelta: 0 }] },
    ],
  },
  {
    id: "clam-chicken-soup",
    name: "鸡汤汆海蚌",
    category: "经典福州菜",
    price: 98,
    image: "🦪",
    tag: "鲜汤",
    rank: 10,
    stock: 16,
    monthlySales: 156,
    description: "清鸡汤汆本港海蚌，汤清味鲜，保留闽菜重汤底的特点",
    specs: [
      { name: "规格", options: [{ label: "例份", priceDelta: 0 }, { label: "加海蚌", priceDelta: 36 }] },
    ],
  },
  {
    id: "red-crab-rice",
    name: "红蟳米糕",
    category: "烟台山新派",
    price: 128,
    image: "🦀",
    tag: "江景同款",
    rank: 3,
    stock: 20,
    monthlySales: 386,
    description: "红蟳膏香渗入糯米，虾米、香菇、干贝同焖，鲜香糯润",
    specs: [
      { name: "规格", options: [{ label: "半只红蟳", priceDelta: 0 }, { label: "整只红蟳", priceDelta: 88 }] },
    ],
  },
  {
    id: "sesame-oil-prawns",
    name: "香油明虾",
    category: "烟台山新派",
    price: 88,
    image: "🦐",
    tag: "海味",
    rank: 7,
    stock: 30,
    monthlySales: 248,
    description: "明虾煎香后淋热香油，虾壳酥、虾肉弹，适合分享",
    specs: [
      { name: "份量", options: [{ label: "6 只", priceDelta: 0 }, { label: "10 只", priceDelta: 48 }] },
      { name: "口味", options: [{ label: "香油原味", priceDelta: 0 }, { label: "蒜香", priceDelta: 0 }] },
    ],
  },
  {
    id: "minjiang-white-fish",
    name: "闽江白刀鱼",
    category: "烟台山新派",
    price: 98,
    image: "🐟",
    tag: "时令",
    rank: 9,
    stock: 14,
    monthlySales: 142,
    description: "清蒸白刀鱼，葱姜豉油提鲜，灵感来自闽江边烟台山餐厅风味",
    specs: [
      { name: "做法", options: [{ label: "清蒸", priceDelta: 0 }, { label: "葱油", priceDelta: 0 }] },
    ],
  },
  {
    id: "jasmine-smoked-chicken",
    name: "茉莉花茶熏鸡",
    category: "烟台山新派",
    price: 68,
    image: "🍗",
    tag: "创新",
    rank: 6,
    stock: 32,
    monthlySales: 286,
    description: "以福州茉莉花茶香入菜，鸡皮微脆，茶香清爽解腻",
    specs: [
      { name: "份量", options: [{ label: "半只", priceDelta: 0 }, { label: "整只", priceDelta: 58 }] },
      { name: "口味", options: [{ label: "茶香原味", priceDelta: 0 }, { label: "椒盐", priceDelta: 0 }] },
    ],
  },
  {
    id: "red-wine-oyster-tofu",
    name: "红糟海蛎豆腐煲",
    category: "烟台山新派",
    price: 58,
    image: "🥘",
    tag: "下饭",
    rank: 11,
    stock: 36,
    monthlySales: 226,
    description: "福州红糟、海蛎、嫩豆腐同煲，鲜甜带糟香",
    specs: [
      { name: "口味", options: [{ label: "红糟原味", priceDelta: 0 }, { label: "微辣", priceDelta: 0 }] },
      { name: "加料", options: [{ label: "不加料", priceDelta: 0 }, { label: "加海蛎", priceDelta: 18 }] },
    ],
  },
  {
    id: "fuzhou-fish-ball-soup",
    name: "福州鱼丸汤",
    category: "主食小吃",
    price: 22,
    image: "🍡",
    tag: "本地小吃",
    rank: 12,
    stock: 80,
    monthlySales: 462,
    description: "鱼浆包肉馅，咬开爆汁，清汤加葱珠",
    specs: [
      { name: "数量", options: [{ label: "6 粒", priceDelta: 0 }, { label: "10 粒", priceDelta: 12 }] },
      { name: "汤底", options: [{ label: "清汤", priceDelta: 0 }, { label: "鱼露胡椒", priceDelta: 0 }] },
    ],
  },
  {
    id: "taiping-yan",
    name: "太平燕",
    category: "主食小吃",
    price: 24,
    image: "🥣",
    tag: "福州味",
    rank: 13,
    stock: 66,
    monthlySales: 408,
    description: "肉燕皮薄馅香，配鸭蛋寓意太平，适合早餐或夜宵",
    specs: [
      { name: "规格", options: [{ label: "常规", priceDelta: 0 }, { label: "加燕", priceDelta: 8 }] },
      { name: "口味", options: [{ label: "清汤", priceDelta: 0 }, { label: "胡椒重", priceDelta: 0 }] },
    ],
  },
  {
    id: "guobianhu",
    name: "海鲜锅边糊",
    category: "主食小吃",
    price: 18,
    image: "🍜",
    tag: "早餐王",
    rank: 14,
    stock: 72,
    monthlySales: 386,
    description: "米浆锅边刮片，虾皮、蛤蜊、香菇熬汤，福州人气小吃",
    specs: [
      { name: "加料", options: [{ label: "标准", priceDelta: 0 }, { label: "加鱼丸", priceDelta: 8 }, { label: "加海蛎", priceDelta: 10 }] },
    ],
  },
  {
    id: "oyster-cake",
    name: "海蛎饼",
    category: "主食小吃",
    price: 8,
    image: "🫓",
    tag: "现炸",
    rank: 15,
    stock: 120,
    monthlySales: 520,
    description: "米浆包海蛎、紫菜、包菜现炸，外壳酥脆",
    specs: [
      { name: "数量", options: [{ label: "1 个", priceDelta: 0 }, { label: "3 个", priceDelta: 14 }] },
      { name: "蘸料", options: [{ label: "甜辣酱", priceDelta: 0 }, { label: "不加酱", priceDelta: 0 }] },
    ],
  },
  {
    id: "ban-fen-gan",
    name: "葱油拌粉干",
    category: "主食小吃",
    price: 18,
    image: "🍝",
    tag: "快手",
    rank: 16,
    stock: 88,
    monthlySales: 338,
    description: "福州粉干拌葱油、鱼露、花生碎，适合搭鱼丸汤",
    specs: [
      { name: "份量", options: [{ label: "标准", priceDelta: 0 }, { label: "加粉", priceDelta: 5 }] },
      { name: "辣度", options: [{ label: "不辣", priceDelta: 0 }, { label: "微辣", priceDelta: 0 }] },
    ],
  },
  {
    id: "eight-treasure-taro",
    name: "八宝芋泥",
    category: "甜品饮品",
    price: 26,
    image: "🍠",
    tag: "甜品",
    rank: 17,
    stock: 42,
    monthlySales: 268,
    description: "槟榔芋蒸透压泥，配莲子、红枣、瓜子仁，甜而不腻",
    specs: [
      { name: "温度", options: [{ label: "热", priceDelta: 0 }, { label: "微温", priceDelta: 0 }] },
      { name: "甜度", options: [{ label: "标准", priceDelta: 0 }, { label: "少糖", priceDelta: 0 }] },
    ],
  },
  {
    id: "jasmine-shihuadong",
    name: "茉莉石花冻",
    category: "甜品饮品",
    price: 18,
    image: "🍧",
    tag: "烟台山风",
    rank: 18,
    stock: 76,
    monthlySales: 356,
    description: "石花膏清爽滑嫩，加入茉莉蜜和青柠，适合饭后解腻",
    specs: [
      { name: "冰量", options: [{ label: "少冰", priceDelta: 0 }, { label: "正常冰", priceDelta: 0 }, { label: "去冰", priceDelta: 0 }] },
      { name: "甜度", options: [{ label: "三分糖", priceDelta: 0 }, { label: "五分糖", priceDelta: 0 }] },
    ],
  },
  {
    id: "olive-jasmine-sparkling",
    name: "橄榄茉莉气泡饮",
    category: "甜品饮品",
    price: 16,
    image: "🥤",
    tag: "清爽",
    rank: 19,
    stock: 90,
    monthlySales: 318,
    description: "福州橄榄的回甘配茉莉茶香，气泡感清爽",
    specs: [
      { name: "冰量", options: [{ label: "少冰", priceDelta: 0 }, { label: "正常冰", priceDelta: 0 }, { label: "去冰", priceDelta: 0 }] },
      { name: "甜度", options: [{ label: "无糖", priceDelta: 0 }, { label: "三分糖", priceDelta: 0 }, { label: "五分糖", priceDelta: 0 }] },
    ],
  },
];
