// 以后你主要改这个文件就能调整菜品。
// id 不能重复；category 会自动生成左侧分类；image 可以用 emoji，也可以换成图片地址。
window.MENU_ITEMS = [
  {
    id: "beef-noodle",
    name: "招牌牛肉面",
    category: "主食",
    price: 28,
    image: "🍜",
    tag: "热卖",
    description: "牛腱肉、手工面、浓郁清汤底",
  },
  {
    id: "rice-chicken",
    name: "照烧鸡腿饭",
    category: "主食",
    price: 32,
    image: "🍱",
    tag: "推荐",
    description: "去骨鸡腿、温泉蛋、时蔬配菜",
  },
  {
    id: "dumpling",
    name: "鲜肉水饺",
    category: "主食",
    price: 24,
    image: "🥟",
    tag: "",
    description: "现包水饺，搭配蒜香蘸汁",
  },
  {
    id: "spicy-chicken",
    name: "辣子鸡丁",
    category: "热菜",
    price: 46,
    image: "🍗",
    tag: "微辣",
    description: "外酥里嫩，花椒香气足",
  },
  {
    id: "fish",
    name: "酸菜鱼",
    category: "热菜",
    price: 68,
    image: "🐟",
    tag: "招牌",
    description: "黑鱼片、酸菜、金汤酸辣口",
  },
  {
    id: "tofu",
    name: "家常豆腐",
    category: "热菜",
    price: 26,
    image: "🥘",
    tag: "素食",
    description: "豆腐煎香，酱汁浓郁下饭",
  },
  {
    id: "cucumber",
    name: "拍黄瓜",
    category: "凉菜",
    price: 16,
    image: "🥒",
    tag: "清爽",
    description: "蒜香醋汁，开胃解腻",
  },
  {
    id: "salad",
    name: "田园沙拉",
    category: "凉菜",
    price: 22,
    image: "🥗",
    tag: "低脂",
    description: "新鲜蔬菜、玉米、油醋汁",
  },
  {
    id: "milk-tea",
    name: "茉莉奶绿",
    category: "饮品",
    price: 18,
    image: "🧋",
    tag: "冰/热",
    description: "茉莉茶底，奶香轻盈",
  },
  {
    id: "lemon-tea",
    name: "手打柠檬茶",
    category: "饮品",
    price: 16,
    image: "🍋",
    tag: "",
    description: "清新酸甜，默认少冰",
  },
];
